# time.py

from enum import Enum

class Time(Enum):

    TRADING_DAYS = 252
    MINUTES_IN_HOURS = 60
    HOURS_IN_TRADING_DAY = 6.5
    MINUTE_BARS = TRADING_DAYS * MINUTES_IN_HOURS * HOURS_IN_TRADING_DAY
    HOURS_BARS = TRADING_DAYS * HOURS_IN_TRADING_DAY
    DAY_BARS = TRADING_DAYS
